import { useNavigate } from 'react-router-dom'
import { useState, useEffect } from 'react'

const ROLES = ['Software Engineer', 'Frontend Engineer', 'Backend Engineer', 'Full Stack Engineer', 'Data Scientist', 'Product Manager']
const STATS = [
  { value: '10K+', label: 'Interviews Practiced' },
  { value: '94%', label: 'User Satisfaction' },
  { value: '3x', label: 'Faster Improvement' },
  { value: '500+', label: 'Questions Generated Daily' },
]
const FEATURES = [
  {
    icon: '🤖',
    title: 'Claude AI Powered',
    desc: 'Every question is uniquely generated by Claude, Anthropic\'s most advanced AI. No recycled question banks — real interview simulation every time.',
    color: 'var(--purple)',
  },
  {
    icon: '📊',
    title: 'Multi-Dimensional Scoring',
    desc: 'Get scored on Correctness, Clarity, Relevance and Communication. Know exactly where you stand and what to improve.',
    color: 'var(--cyan)',
  },
  {
    icon: '🎯',
    title: 'Role-Specific Questions',
    desc: 'Whether you\'re targeting FAANG or a startup, questions are tailored to your exact role and seniority level.',
    color: 'var(--green)',
  },
  {
    icon: '🎤',
    title: 'Voice Input',
    desc: 'Answer like you\'re in a real interview — speak your answers out loud and get evaluated on your verbal communication.',
    color: 'var(--yellow)',
  },
  {
    icon: '⚡',
    title: 'Instant Feedback',
    desc: 'No waiting days for feedback. Get detailed AI analysis in seconds — strengths, improvements, ideal answer, and next steps.',
    color: 'var(--purple-bright)',
  },
  {
    icon: '📈',
    title: 'Track Your Progress',
    desc: 'See your scores improve over time. Every session is saved so you can measure your growth and double down on weak areas.',
    color: 'var(--cyan)',
  },
]

const TESTIMONIALS = [
  { name: 'Alex Chen', role: 'SWE Intern @ Google', avatar: '👨‍💻', text: 'InterviewGhost helped me go from bombing every technical question to landing my dream Google internship. The AI feedback is incredibly specific.', score: 94 },
  { name: 'Priya Sharma', role: 'PM Intern @ Meta', avatar: '👩‍💼', text: 'I practiced every day for 2 weeks before my Meta interview. The behavioral question coaching was exactly what I needed.', score: 91 },
  { name: 'Marcus Johnson', role: 'Frontend Intern @ Stripe', avatar: '👨‍🎨', text: 'The voice input feature is insane. Practicing out loud made such a difference. Got my Stripe offer after just 10 sessions.', score: 88 },
]

export default function Landing() {
  const navigate = useNavigate()
  const [roleIndex, setRoleIndex] = useState(0)
  const [displayed, setDisplayed] = useState('')
  const [isDeleting, setIsDeleting] = useState(false)

  // Typewriter effect
  useEffect(() => {
    const current = ROLES[roleIndex]
    let timeout

    if (!isDeleting && displayed.length < current.length) {
      timeout = setTimeout(() => setDisplayed(current.slice(0, displayed.length + 1)), 80)
    } else if (!isDeleting && displayed.length === current.length) {
      timeout = setTimeout(() => setIsDeleting(true), 2000)
    } else if (isDeleting && displayed.length > 0) {
      timeout = setTimeout(() => setDisplayed(displayed.slice(0, -1)), 40)
    } else if (isDeleting && displayed.length === 0) {
      setIsDeleting(false)
      setRoleIndex((roleIndex + 1) % ROLES.length)
    }

    return () => clearTimeout(timeout)
  }, [displayed, isDeleting, roleIndex])

  return (
    <div style={styles.page}>
      {/* Ambient background */}
      <div style={styles.orb1} />
      <div style={styles.orb2} />
      <div style={styles.orb3} />
      <div style={styles.grid} />

      {/* NAVBAR */}
      <nav style={styles.nav}>
        <div style={styles.navInner}>
          <div style={styles.navLogo}>
            <span style={styles.navGhost}>👻</span>
            <span style={styles.navBrand}>
              Interview<span className="gradient-text">Ghost</span>
            </span>
          </div>
          <div style={styles.navLinks}>
            <a href="#features" style={styles.navLink}>Features</a>
            <a href="#testimonials" style={styles.navLink}>Stories</a>
            <a href="#pricing" style={styles.navLink}>Pricing</a>
          </div>
          <div style={styles.navActions}>
            <button style={styles.navLoginBtn} onClick={() => navigate('/login')}>
              Sign In
            </button>
            <button className="btn-primary" style={styles.navCTABtn} onClick={() => navigate('/register')}>
              Start Free →
            </button>
          </div>
        </div>
      </nav>

      {/* HERO */}
      <section style={styles.hero}>
        <div className="animate-fade-up stagger-1" style={styles.heroBadge}>
          <span style={styles.heroBadgeDot} />
          Powered by Claude AI · Built for ambitious students
        </div>

        <h1 className="animate-fade-up stagger-2" style={styles.heroTitle}>
          Ace your interview as a<br />
          <span style={styles.heroRoleWrap}>
            <span className="gradient-text">{displayed}</span>
            <span style={styles.cursor}>|</span>
          </span>
        </h1>

        <p className="animate-fade-up stagger-3" style={styles.heroSub}>
          The AI-powered interview coach that gives you real questions,<br />
          instant feedback, and the confidence to land your dream job.
        </p>

        <div className="animate-fade-up stagger-4" style={styles.heroActions}>
          <button
            className="btn-primary"
            style={styles.heroCTA}
            onClick={() => navigate('/register')}
          >
            🚀 Start Practicing Free
          </button>
          <button style={styles.heroSecondary} onClick={() => navigate('/login')}>
            Already have an account →
          </button>
        </div>

        {/* Social proof */}
        <div className="animate-fade-up stagger-5" style={styles.socialProof}>
          <div style={styles.avatarStack}>
            {['👨‍💻','👩‍💻','👨‍🎨','👩‍🔬','👨‍💼'].map((a, i) => (
              <div key={i} style={{ ...styles.avatar, marginLeft: i > 0 ? '-10px' : 0 }}>
                {a}
              </div>
            ))}
          </div>
          <span style={styles.socialText}>
            Join <strong style={{ color: 'var(--text-primary)' }}>2,400+</strong> students already practicing
          </span>
        </div>

        {/* Hero visual */}
        <div className="animate-fade-up stagger-5" style={styles.heroVisual}>
          <div style={styles.mockCard}>
            <div style={styles.mockHeader}>
              <div style={styles.mockDots}>
                <div style={{ ...styles.mockDot, background: '#ff5f57' }} />
                <div style={{ ...styles.mockDot, background: '#febc2e' }} />
                <div style={{ ...styles.mockDot, background: '#28c840' }} />
              </div>
              <span style={styles.mockTitle}>InterviewGhost · Software Engineer Intern</span>
            </div>
            <div style={styles.mockBody}>
              <div style={styles.mockQuestion}>
                <div style={styles.mockBadges}>
                  <span className="badge badge-purple">Technical</span>
                  <span className="badge badge-yellow">Medium</span>
                </div>
                <p style={styles.mockQuestionText}>
                  Explain the difference between a stack and a queue. Implement a queue using two stacks.
                </p>
              </div>
              <div style={styles.mockScores}>
                {[
                  { label: 'Correctness', score: 88, color: 'var(--green)' },
                  { label: 'Clarity', score: 92, color: 'var(--cyan)' },
                  { label: 'Communication', score: 85, color: 'var(--purple-bright)' },
                ].map(({ label, score, color }) => (
                  <div key={label} style={styles.mockScoreRow}>
                    <span style={styles.mockScoreLabel}>{label}</span>
                    <div style={styles.mockScoreBar}>
                      <div style={{ ...styles.mockScoreFill, width: `${score}%`, background: color }} />
                    </div>
                    <span style={{ ...styles.mockScoreNum, color }}>{score}</span>
                  </div>
                ))}
              </div>
              <div style={styles.mockFeedback}>
                <span style={{ color: 'var(--green)', fontSize: '12px' }}>💪 Strong conceptual understanding with excellent real-world examples...</span>
              </div>
            </div>
          </div>
          {/* Floating badges */}
          <div style={styles.floatBadge1} className="animate-float">
            <span>🎯</span> 87% Success Rate
          </div>
          <div style={styles.floatBadge2} className="animate-float" >
            <span>⚡</span> Instant AI Feedback
          </div>
        </div>
      </section>

      {/* STATS */}
      <section style={styles.statsSection}>
        <div style={styles.statsInner}>
          {STATS.map((s, i) => (
            <div key={i} style={styles.statItem}>
              <div style={styles.statValue}>{s.value}</div>
              <div style={styles.statLabel}>{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* FEATURES */}
      <section id="features" style={styles.section}>
        <div style={styles.sectionInner}>
          <div style={styles.sectionBadge}>Features</div>
          <h2 style={styles.sectionTitle}>
            Everything you need to<br />
            <span className="gradient-text">land the offer</span>
          </h2>
          <p style={styles.sectionSub}>
            Built by a student, for students. Every feature designed to simulate real interviews and accelerate your growth.
          </p>
          <div style={styles.featuresGrid}>
            {FEATURES.map((f, i) => (
              <div key={i} style={styles.featureCard} className="glass">
                <div style={{ ...styles.featureIcon, background: `${f.color}15`, border: `1px solid ${f.color}30` }}>
                  {f.icon}
                </div>
                <h3 style={styles.featureTitle}>{f.title}</h3>
                <p style={styles.featureDesc}>{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* TESTIMONIALS */}
      <section id="testimonials" style={styles.section}>
        <div style={styles.sectionInner}>
          <div style={styles.sectionBadge}>Success Stories</div>
          <h2 style={styles.sectionTitle}>
            Students who got<br />
            <span className="gradient-text">their dream offers</span>
          </h2>
          <div style={styles.testimonialsGrid}>
            {TESTIMONIALS.map((t, i) => (
              <div key={i} style={styles.testimonialCard} className="glass">
                <div style={styles.testimonialHeader}>
                  <div style={styles.testimonialAvatar}>{t.avatar}</div>
                  <div>
                    <div style={styles.testimonialName}>{t.name}</div>
                    <div style={styles.testimonialRole}>{t.role}</div>
                  </div>
                  <div style={styles.testimonialScore}>
                    <div style={styles.testimonialScoreNum}>{t.score}</div>
                    <div style={styles.testimonialScoreLabel}>avg score</div>
                  </div>
                </div>
                <p style={styles.testimonialText}>"{t.text}"</p>
                <div style={styles.testimonialStars}>{'⭐'.repeat(5)}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section id="pricing" style={styles.section}>
        <div style={styles.sectionInner}>
          <div style={styles.sectionBadge}>Pricing</div>
          <h2 style={styles.sectionTitle}>
            Start free.<br />
            <span className="gradient-text">Upgrade when ready.</span>
          </h2>
          <div style={styles.pricingGrid}>
            {/* Free */}
            <div style={styles.pricingCard} className="glass">
              <div style={styles.pricingName}>Free</div>
              <div style={styles.pricingPrice}>$0<span style={styles.pricingPer}>/month</span></div>
              <div style={styles.pricingDesc}>Perfect to get started</div>
              <div style={styles.pricingFeatures}>
                {['5 sessions/month', 'All 8 roles', 'AI scoring', 'Basic feedback'].map(f => (
                  <div key={f} style={styles.pricingFeature}>
                    <span style={{ color: 'var(--green)' }}>✓</span> {f}
                  </div>
                ))}
              </div>
              <button className="btn-primary" style={styles.pricingBtn} onClick={() => navigate('/register')}>
                Get Started Free
              </button>
            </div>
            {/* Pro */}
            <div style={{ ...styles.pricingCard, ...styles.pricingCardPro }}>
              <div style={styles.pricingProBadge}>Most Popular</div>
              <div style={styles.pricingName}>Pro</div>
              <div style={{ ...styles.pricingPrice, color: 'var(--purple-bright)' }}>
                $12<span style={styles.pricingPer}>/month</span>
              </div>
              <div style={styles.pricingDesc}>For serious candidates</div>
              <div style={styles.pricingFeatures}>
                {['Unlimited sessions', 'All 8 roles', 'Advanced AI scoring', 'Detailed feedback', 'Progress tracking', 'Voice input', 'Streak system', 'Priority support'].map(f => (
                  <div key={f} style={styles.pricingFeature}>
                    <span style={{ color: 'var(--purple-bright)' }}>✓</span> {f}
                  </div>
                ))}
              </div>
              <button className="btn-primary" style={{ ...styles.pricingBtn, animation: 'pulse-glow 2s ease infinite' }} onClick={() => navigate('/register')}>
                Start Pro Trial →
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* FINAL CTA */}
      <section style={styles.ctaSection}>
        <div style={styles.ctaInner}>
          <div className="animate-float" style={styles.ctaGhost}>👻</div>
          <h2 style={styles.ctaTitle}>
            Your dream internship<br />
            <span className="gradient-text">is one practice away.</span>
          </h2>
          <p style={styles.ctaSub}>
            Join thousands of students who used InterviewGhost to land offers at Google, Meta, Apple, and more.
          </p>
          <button className="btn-primary" style={styles.ctaBtn} onClick={() => navigate('/register')}>
            🚀 Start Practicing Free Today
          </button>
        </div>
      </section>

      {/* FOOTER */}
      <footer style={styles.footer}>
        <div style={styles.footerInner}>
          <div style={styles.footerLogo}>
            <span>👻</span>
            <span style={styles.footerBrand}>
              Interview<span className="gradient-text">Ghost</span>
            </span>
          </div>
          <div style={styles.footerText}>
            Built with 💜 by a sophomore who wanted to ace his own interviews.
          </div>
          <div style={styles.footerText}>© 2026 InterviewGhost. All rights reserved.</div>
        </div>
      </footer>
    </div>
  )
}

const styles = {
  page: { background: 'var(--bg-primary)', minHeight: '100vh', overflowX: 'hidden', position: 'relative' },
  orb1: { position: 'fixed', top: '-20%', left: '-10%', width: '700px', height: '700px', background: 'radial-gradient(circle, rgba(139,92,246,0.12) 0%, transparent 70%)', borderRadius: '50%', pointerEvents: 'none', zIndex: 0, animation: 'orb-float 10s ease-in-out infinite' },
  orb2: { position: 'fixed', top: '30%', right: '-10%', width: '600px', height: '600px', background: 'radial-gradient(circle, rgba(34,211,238,0.08) 0%, transparent 70%)', borderRadius: '50%', pointerEvents: 'none', zIndex: 0, animation: 'orb-float 14s ease-in-out infinite reverse' },
  orb3: { position: 'fixed', bottom: '-20%', left: '30%', width: '500px', height: '500px', background: 'radial-gradient(circle, rgba(139,92,246,0.08) 0%, transparent 70%)', borderRadius: '50%', pointerEvents: 'none', zIndex: 0, animation: 'orb-float 12s ease-in-out infinite' },
  grid: { position: 'fixed', inset: 0, zIndex: 0, backgroundImage: 'linear-gradient(rgba(139,92,246,0.025) 1px, transparent 1px), linear-gradient(90deg, rgba(139,92,246,0.025) 1px, transparent 1px)', backgroundSize: '40px 40px', pointerEvents: 'none' },
  nav: { position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100, padding: '0 24px', background: 'rgba(5,5,8,0.8)', backdropFilter: 'blur(20px)', borderBottom: '1px solid rgba(255,255,255,0.06)' },
  navInner: { maxWidth: '1100px', margin: '0 auto', height: '64px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  navLogo: { display: 'flex', alignItems: 'center', gap: '10px' },
  navGhost: { fontSize: '24px' },
  navBrand: { fontFamily: 'var(--font-display)', fontSize: '20px', fontWeight: 800, letterSpacing: '-0.02em' },
  navLinks: { display: 'flex', gap: '32px' },
  navLink: { color: 'var(--text-muted)', textDecoration: 'none', fontSize: '14px', fontWeight: 500, transition: 'color 0.2s ease' },
  navActions: { display: 'flex', gap: '12px', alignItems: 'center' },
  navLoginBtn: { background: 'transparent', border: '1px solid rgba(255,255,255,0.1)', color: 'var(--text-secondary)', padding: '8px 18px', borderRadius: '8px', cursor: 'pointer', fontSize: '14px', fontFamily: 'var(--font-body)', transition: 'all 0.2s ease' },
  navCTABtn: { padding: '8px 20px', fontSize: '14px' },
  hero: { position: 'relative', zIndex: 1, paddingTop: '140px', paddingBottom: '80px', textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '24px', padding: '140px 24px 80px' },
  heroBadge: { display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '8px 18px', borderRadius: '50px', background: 'rgba(139,92,246,0.1)', border: '1px solid rgba(139,92,246,0.2)', color: 'var(--purple-bright)', fontSize: '13px', fontWeight: 500 },
  heroBadgeDot: { width: '6px', height: '6px', borderRadius: '50%', background: 'var(--purple-bright)', boxShadow: '0 0 8px var(--purple-glow)', display: 'inline-block' },
  heroTitle: { fontFamily: 'var(--font-display)', fontSize: 'clamp(40px, 6vw, 80px)', fontWeight: 800, lineHeight: 1.1, letterSpacing: '-0.03em', maxWidth: '900px' },
  heroRoleWrap: { display: 'inline-flex', alignItems: 'center', minWidth: '500px', justifyContent: 'center' },
  cursor: { color: 'var(--purple-bright)', animation: 'fadeIn 0.5s ease infinite alternate', marginLeft: '2px' },
  heroSub: { color: 'var(--text-secondary)', fontSize: '18px', lineHeight: 1.7, maxWidth: '580px' },
  heroActions: { display: 'flex', gap: '16px', alignItems: 'center', flexWrap: 'wrap', justifyContent: 'center' },
  heroCTA: { padding: '16px 36px', fontSize: '16px', fontWeight: 700 },
  heroSecondary: { background: 'transparent', border: 'none', color: 'var(--text-muted)', fontSize: '15px', cursor: 'pointer', fontFamily: 'var(--font-body)', transition: 'color 0.2s ease' },
  socialProof: { display: 'flex', alignItems: 'center', gap: '12px' },
  avatarStack: { display: 'flex' },
  avatar: { width: '32px', height: '32px', borderRadius: '50%', background: 'rgba(139,92,246,0.2)', border: '2px solid var(--bg-primary)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '16px' },
  socialText: { color: 'var(--text-muted)', fontSize: '14px' },
  heroVisual: { position: 'relative', width: '100%', maxWidth: '720px', marginTop: '24px' },
  mockCard: { background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 40px 80px rgba(0,0,0,0.4), 0 0 0 1px rgba(139,92,246,0.1)' },
  mockHeader: { display: 'flex', alignItems: 'center', gap: '12px', padding: '14px 20px', background: 'rgba(255,255,255,0.03)', borderBottom: '1px solid rgba(255,255,255,0.06)' },
  mockDots: { display: 'flex', gap: '6px' },
  mockDot: { width: '10px', height: '10px', borderRadius: '50%' },
  mockTitle: { color: 'var(--text-muted)', fontSize: '12px', fontFamily: 'var(--font-mono)' },
  mockBody: { padding: '24px', display: 'flex', flexDirection: 'column', gap: '20px' },
  mockQuestion: { display: 'flex', flexDirection: 'column', gap: '12px' },
  mockBadges: { display: 'flex', gap: '8px' },
  mockQuestionText: { color: 'var(--text-primary)', fontSize: '15px', lineHeight: 1.6, textAlign: 'left' },
  mockScores: { display: 'flex', flexDirection: 'column', gap: '10px' },
  mockScoreRow: { display: 'flex', alignItems: 'center', gap: '12px' },
  mockScoreLabel: { color: 'var(--text-muted)', fontSize: '12px', width: '120px', textAlign: 'left' },
  mockScoreBar: { flex: 1, height: '6px', background: 'rgba(255,255,255,0.06)', borderRadius: '3px', overflow: 'hidden' },
  mockScoreFill: { height: '100%', borderRadius: '3px' },
  mockScoreNum: { fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 600, width: '30px', textAlign: 'right' },
  mockFeedback: { padding: '12px 16px', background: 'rgba(16,185,129,0.05)', border: '1px solid rgba(16,185,129,0.1)', borderRadius: '10px', textAlign: 'left' },
  floatBadge1: { position: 'absolute', top: '-20px', right: '-20px', background: 'rgba(139,92,246,0.15)', backdropFilter: 'blur(10px)', border: '1px solid rgba(139,92,246,0.3)', borderRadius: '50px', padding: '10px 18px', color: 'var(--purple-bright)', fontSize: '13px', fontWeight: 600, display: 'flex', gap: '8px', alignItems: 'center', animationDelay: '0.5s' },
  floatBadge2: { position: 'absolute', bottom: '-20px', left: '-20px', background: 'rgba(34,211,238,0.1)', backdropFilter: 'blur(10px)', border: '1px solid rgba(34,211,238,0.2)', borderRadius: '50px', padding: '10px 18px', color: 'var(--cyan)', fontSize: '13px', fontWeight: 600, display: 'flex', gap: '8px', alignItems: 'center', animationDelay: '1s' },
  statsSection: { position: 'relative', zIndex: 1, borderTop: '1px solid rgba(255,255,255,0.06)', borderBottom: '1px solid rgba(255,255,255,0.06)', background: 'rgba(255,255,255,0.02)', padding: '48px 24px' },
  statsInner: { maxWidth: '900px', margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '32px' },
  statItem: { textAlign: 'center' },
  statValue: { fontFamily: 'var(--font-display)', fontSize: '42px', fontWeight: 800, background: 'linear-gradient(135deg, var(--purple-bright), var(--cyan))', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' },
  statLabel: { color: 'var(--text-muted)', fontSize: '14px', marginTop: '4px' },
  section: { position: 'relative', zIndex: 1, padding: '100px 24px' },
  sectionInner: { maxWidth: '1100px', margin: '0 auto', textAlign: 'center' },
  sectionBadge: { display: 'inline-block', padding: '6px 16px', borderRadius: '50px', background: 'rgba(139,92,246,0.1)', border: '1px solid rgba(139,92,246,0.2)', color: 'var(--purple-bright)', fontSize: '12px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '20px' },
  sectionTitle: { fontFamily: 'var(--font-display)', fontSize: 'clamp(32px, 4vw, 52px)', fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.2, marginBottom: '16px' },
  sectionSub: { color: 'var(--text-secondary)', fontSize: '17px', lineHeight: 1.7, maxWidth: '540px', margin: '0 auto 56px' },
  featuresGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px', textAlign: 'left' },
  featureCard: { padding: '28px', borderRadius: '20px', display: 'flex', flexDirection: 'column', gap: '14px' },
  featureIcon: { width: '48px', height: '48px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '22px' },
  featureTitle: { fontFamily: 'var(--font-display)', fontSize: '17px', fontWeight: 700 },
  featureDesc: { color: 'var(--text-secondary)', fontSize: '14px', lineHeight: 1.7 },
  testimonialsGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px', textAlign: 'left' },
  testimonialCard: { padding: '28px', display: 'flex', flexDirection: 'column', gap: '16px' },
  testimonialHeader: { display: 'flex', alignItems: 'center', gap: '12px' },
  testimonialAvatar: { width: '44px', height: '44px', borderRadius: '50%', background: 'rgba(139,92,246,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '22px', flexShrink: 0 },
  testimonialName: { fontWeight: 700, fontSize: '15px' },
  testimonialRole: { color: 'var(--purple-bright)', fontSize: '12px' },
  testimonialScore: { marginLeft: 'auto', textAlign: 'center' },
  testimonialScoreNum: { fontFamily: 'var(--font-mono)', fontSize: '24px', fontWeight: 700, color: 'var(--green)' },
  testimonialScoreLabel: { color: 'var(--text-muted)', fontSize: '10px' },
  testimonialText: { color: 'var(--text-secondary)', fontSize: '14px', lineHeight: 1.7 },
  testimonialStars: { fontSize: '12px' },
  pricingGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '20px', maxWidth: '700px', margin: '0 auto', textAlign: 'left' },
  pricingCard: { padding: '32px', borderRadius: '24px', display: 'flex', flexDirection: 'column', gap: '16px', position: 'relative' },
  pricingCardPro: { background: 'linear-gradient(135deg, rgba(139,92,246,0.1), rgba(34,211,238,0.05))', border: '1px solid rgba(139,92,246,0.3)' },
  pricingProBadge: { position: 'absolute', top: '-12px', left: '50%', transform: 'translateX(-50%)', background: 'linear-gradient(135deg, var(--purple), #6d28d9)', color: '#fff', padding: '4px 16px', borderRadius: '50px', fontSize: '11px', fontWeight: 700, whiteSpace: 'nowrap' },
  pricingName: { fontFamily: 'var(--font-display)', fontSize: '18px', fontWeight: 700 },
  pricingPrice: { fontFamily: 'var(--font-display)', fontSize: '42px', fontWeight: 800 },
  pricingPer: { fontSize: '16px', color: 'var(--text-muted)', fontFamily: 'var(--font-body)' },
  pricingDesc: { color: 'var(--text-muted)', fontSize: '14px' },
  pricingFeatures: { display: 'flex', flexDirection: 'column', gap: '10px', flex: 1 },
  pricingFeature: { color: 'var(--text-secondary)', fontSize: '14px', display: 'flex', gap: '8px' },
  pricingBtn: { width: '100%', padding: '14px', fontSize: '15px', marginTop: '8px' },
  ctaSection: { position: 'relative', zIndex: 1, padding: '100px 24px', textAlign: 'center', background: 'linear-gradient(135deg, rgba(139,92,246,0.06), rgba(34,211,238,0.03))' },
  ctaInner: { maxWidth: '700px', margin: '0 auto', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '24px' },
  ctaGhost: { fontSize: '72px' },
  ctaTitle: { fontFamily: 'var(--font-display)', fontSize: 'clamp(32px, 4vw, 52px)', fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.2 },
  ctaSub: { color: 'var(--text-secondary)', fontSize: '17px', lineHeight: 1.7 },
  ctaBtn: { padding: '18px 48px', fontSize: '17px', fontWeight: 700 },
  footer: { position: 'relative', zIndex: 1, borderTop: '1px solid rgba(255,255,255,0.06)', padding: '40px 24px' },
  footerInner: { maxWidth: '1100px', margin: '0 auto', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '12px', textAlign: 'center' },
  footerLogo: { display: 'flex', alignItems: 'center', gap: '8px' },
  footerBrand: { fontFamily: 'var(--font-display)', fontSize: '18px', fontWeight: 800 },
  footerText: { color: 'var(--text-muted)', fontSize: '13px' },
}