import { useNavigate, Navigate } from 'react-router-dom'
import { useState, useEffect } from 'react'
import { useAuth } from '../context/AuthContext'

const ROLES = ['Software Engineer', 'Frontend Engineer', 'Backend Engineer', 'Full Stack Engineer', 'Data Scientist', 'Product Manager']
const STATS = [
    { value: '8', label: 'Roles Supported' },
{ value: '5', label: 'Questions Per Session' },
{ value: '4', label: 'Score Dimensions' },
{ value: '∞', label: 'Unique AI Questions' },
]
const FEATURES = [
  { icon: '✨', title: 'AI Powered', desc: "Every question is uniquely generated by advanced AI. No recycled question banks — real interview simulation every time.", color: 'var(--purple)' },
  { icon: '📊', title: 'Multi-Dimensional Scoring', desc: 'Get scored on Correctness, Clarity, Relevance and Communication. Know exactly where you stand and what to improve.', color: 'var(--cyan)' },
  { icon: '🎯', title: 'Role-Specific Questions', desc: "Whether you're targeting FAANG or a startup, questions are tailored to your exact role and seniority level.", color: 'var(--green)' },
  { icon: '🎤', title: 'Voice Input', desc: "Answer like you're in a real interview — speak your answers out loud and get evaluated on your verbal communication.", color: 'var(--yellow)' },
  { icon: '⚡', title: 'Instant Feedback', desc: 'No waiting days for feedback. Get detailed AI analysis in seconds — strengths, improvements, ideal answer, and next steps.', color: 'var(--purple-bright)' },
  { icon: '📈', title: 'Track Your Progress', desc: 'See your scores improve over time. Every session is saved so you can measure your growth and double down on weak areas.', color: 'var(--cyan)' },
]
const TESTIMONIALS = [
    { name: 'Smit Kakadiya', role: 'CS Student @ SF State', avatar: '👨‍💻', text: 'I built InterviewGhost because I wanted to stand out in internship recruiting. No recycled questions, no vague feedback — just real AI-powered interview simulation.', score: null, tag: 'Builder' },
    { name: 'Early Access', role: 'Be the first to try it', avatar: '🚀', text: 'InterviewGhost is just launching. Be one of the first students to use it and help shape what it becomes. Free to start, no credit card needed.', score: null, tag: 'New' },
    { name: 'Your Story Here', role: 'Could be you', avatar: '🎯', text: 'Practice with real AI feedback, track your progress, and land your dream internship. Join early and get full access free while we grow.', score: null, tag: 'Soon' },
  ]
const FAQS = [
  { q: 'Is InterviewGhost really free?', a: 'Yes! You can start completely free with 5 sessions per month. No credit card required.' },
  { q: 'How is this different from LeetCode?', a: "LeetCode gives you problems to solve alone. InterviewGhost simulates a real interview — it asks questions, listens to your answers, and gives you detailed feedback just like a real interviewer would." },
  { q: 'What roles does InterviewGhost support?', a: 'We support 8 roles: Software Engineer Intern, Frontend Engineer, Backend Engineer, Full Stack Engineer, Data Scientist, Product Manager, DevOps Engineer, and UX Designer.' },
  { q: 'How does the AI scoring work?', a: 'Your answers are evaluated by AI across 4 dimensions: Correctness, Clarity, Relevance, and Communication. You also get a Success Probability score showing your real chances in an actual interview.' },
  { q: 'Can I use voice input?', a: 'Yes! InterviewGhost supports voice input via your browser microphone. Speak your answers out loud just like a real interview.' },
  { q: 'Who built this?', a: 'InterviewGhost was built by Smit Kakadiya, a sophomore CS student at SF State, who wanted to stand out in internship recruiting and built the tool he wished existed.' },
]

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false)
  return (
    <div onClick={() => setOpen(!open)} style={{
      padding: '20px 24px', borderRadius: '16px', marginBottom: '10px',
      border: `1px solid ${open ? 'rgba(139,92,246,0.3)' : 'rgba(255,255,255,0.06)'}`,
      background: open ? 'rgba(139,92,246,0.05)' : 'rgba(255,255,255,0.02)',
      cursor: 'pointer', transition: 'all 0.2s ease',
    }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <span style={{ color: 'var(--text-primary)', fontWeight: 600, fontSize: '15px' }}>{q}</span>
        <span style={{ color: 'var(--purple-bright)', fontSize: '20px', transition: 'transform 0.2s ease', transform: open ? 'rotate(45deg)' : 'rotate(0deg)', display: 'inline-block', marginLeft: '12px', flexShrink: 0 }}>+</span>
      </div>
      {open && <p style={{ color: 'var(--text-secondary)', fontSize: '14px', lineHeight: 1.7, marginTop: '12px' }}>{a}</p>}
    </div>
  )
}

function useIsMobile() {
  const [isMobile, setIsMobile] = useState(window.innerWidth < 768)
  useEffect(() => {
    const handler = () => setIsMobile(window.innerWidth < 768)
    window.addEventListener('resize', handler)
    return () => window.removeEventListener('resize', handler)
  }, [])
  return isMobile
}

export default function Landing() {
  const { user } = useAuth()
  if (user) return <Navigate to="/dashboard" />
  const navigate = useNavigate()
  const isMobile = useIsMobile()
  const [roleIndex, setRoleIndex] = useState(0)
  const [displayed, setDisplayed] = useState('')
  const [isDeleting, setIsDeleting] = useState(false)

  useEffect(() => {
    const current = ROLES[roleIndex]
    let timeout
    if (!isDeleting && displayed.length < current.length) {
      timeout = setTimeout(() => setDisplayed(current.slice(0, displayed.length + 1)), 80)
    } else if (!isDeleting && displayed.length === current.length) {
      timeout = setTimeout(() => setIsDeleting(true), 2000)
    } else if (isDeleting && displayed.length > 0) {
      timeout = setTimeout(() => setDisplayed(displayed.slice(0, -1)), 40)
    } else if (isDeleting && displayed.length === 0) {
      setIsDeleting(false)
      setRoleIndex((roleIndex + 1) % ROLES.length)
    }
    return () => clearTimeout(timeout)
  }, [displayed, isDeleting, roleIndex])

  const s = makeStyles(isMobile)

  return (
    <div style={s.page}>
      <div style={s.orb1} />
      <div style={s.orb2} />
      <div style={s.orb3} />
      <div style={s.grid} />

      {/* NAVBAR */}
      <nav style={s.nav}>
        <div style={s.navInner}>
          <div style={s.navLogo}>
            <span style={s.navGhost}>👻</span>
            <span style={s.navBrand}>Interview<span className="gradient-text">Ghost</span></span>
          </div>
          {!isMobile && (
            <div style={s.navLinks}>
              <a href="#features" style={s.navLink}>Features</a>
              <a href="#testimonials" style={s.navLink}>Stories</a>
              <a href="#pricing" style={s.navLink}>Pricing</a>
              <a href="#faq" style={s.navLink}>FAQ</a>
            </div>
          )}
          <div style={s.navActions}>
            {!isMobile && (
              <button style={s.navLoginBtn} onClick={() => navigate('/login')}>Sign In</button>
            )}
            <button className="btn-primary" style={s.navCTABtn} onClick={() => navigate('/register')}>Start Free →</button>
          </div>
        </div>
      </nav>

      {/* HERO */}
      <section style={s.hero}>
        <div className="animate-fade-up stagger-1" style={s.heroBadge}>
          <span style={s.heroBadgeDot} />
          Powered by AI · Built for ambitious students
        </div>

        <h1 className="animate-fade-up stagger-2" style={s.heroTitle}>
          Ace your interview as a{' '}
          <span style={s.heroRoleWrap}>
            <span className="gradient-text">{displayed}</span>
            <span style={s.cursor}>|</span>
          </span>
        </h1>

        <p className="animate-fade-up stagger-3" style={s.heroSub}>
          The AI-powered interview coach that gives you real questions,
          instant feedback, and the confidence to land your dream job.
        </p>

        <div className="animate-fade-up stagger-4" style={s.heroActions}>
          <button className="btn-primary" style={s.heroCTA} onClick={() => navigate('/register')}>
            🚀 Start Practicing Free
          </button>
          <button style={s.heroSecondary} onClick={() => navigate('/login')}>
            Already have an account →
          </button>
        </div>

        <div className="animate-fade-up stagger-5" style={s.socialProof}>
          <div style={s.avatarStack}>
            {['👨‍💻','👩‍💻','👨‍🎨','👩‍🔬','👨‍💼'].map((a, i) => (
              <div key={i} style={{ ...s.avatar, marginLeft: i > 0 ? '-10px' : 0 }}>{a}</div>
            ))}
          </div>
          <span style={s.socialText}>
          Be an <strong style={{ color: 'var(--text-primary)' }}>early user</strong> — join free today
          </span>
        </div>

        <div className="animate-fade-up stagger-5" style={s.heroVisual}>
          <div style={s.mockCard}>
            <div style={s.mockHeader}>
              <div style={s.mockDots}>
                <div style={{ ...s.mockDot, background: '#ff5f57' }} />
                <div style={{ ...s.mockDot, background: '#febc2e' }} />
                <div style={{ ...s.mockDot, background: '#28c840' }} />
              </div>
              <span style={s.mockTitle}>InterviewGhost · Software Engineer Intern</span>
            </div>
            <div style={s.mockBody}>
              <div style={s.mockQuestion}>
                <div style={s.mockBadges}>
                  <span className="badge badge-purple">Technical</span>
                  <span className="badge badge-yellow">Medium</span>
                </div>
                <p style={s.mockQuestionText}>Explain the difference between a stack and a queue. Implement a queue using two stacks.</p>
              </div>
              <div style={s.mockScores}>
                {[
                  { label: 'Correctness', score: 88, color: 'var(--green)' },
                  { label: 'Clarity', score: 92, color: 'var(--cyan)' },
                  { label: 'Communication', score: 85, color: 'var(--purple-bright)' },
                ].map(({ label, score, color }) => (
                  <div key={label} style={s.mockScoreRow}>
                    <span style={s.mockScoreLabel}>{label}</span>
                    <div style={s.mockScoreBar}>
                      <div style={{ ...s.mockScoreFill, width: `${score}%`, background: color }} />
                    </div>
                    <span style={{ ...s.mockScoreNum, color }}>{score}</span>
                  </div>
                ))}
              </div>
              <div style={s.mockFeedback}>
                <span style={{ color: 'var(--green)', fontSize: '12px' }}>💪 Strong conceptual understanding with excellent real-world examples...</span>
              </div>
            </div>
          </div>
          {!isMobile && <div style={s.floatBadge1} className="animate-float"><span>🎯</span> 87% Success Rate</div>}
          {!isMobile && <div style={s.floatBadge2} className="animate-float"><span>⚡</span> Instant AI Feedback</div>}
        </div>
      </section>

      {/* STATS */}
      <section style={s.statsSection}>
        <div style={s.statsInner}>
          {STATS.map((stat, i) => (
            <div key={i} style={s.statItem}>
              <div style={s.statValue}>{stat.value}</div>
              <div style={s.statLabel}>{stat.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* FEATURES */}
      <section id="features" style={s.section}>
        <div style={s.sectionInner}>
          <div style={s.sectionBadge}>Features</div>
          <h2 style={s.sectionTitle}>Everything you need to<br /><span className="gradient-text">land the offer</span></h2>
          <p style={s.sectionSub}>Built by a student, for students. Every feature designed to simulate real interviews and accelerate your growth.</p>
          <div style={s.featuresGrid}>
            {FEATURES.map((f, i) => (
              <div key={i} style={s.featureCard} className="glass">
                <div style={{ ...s.featureIcon, background: `${f.color}15`, border: `1px solid ${f.color}30` }}>{f.icon}</div>
                <h3 style={s.featureTitle}>{f.title}</h3>
                <p style={s.featureDesc}>{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* TESTIMONIALS */}
      <section id="testimonials" style={s.section}>
        <div style={s.sectionInner}>
          <div style={s.sectionBadge}>Success Stories</div>
          <h2 style={s.sectionTitle}>Students who got<br /><span className="gradient-text">their dream offers</span></h2>
          <div style={s.testimonialsGrid}>
            {TESTIMONIALS.map((t, i) => (
              <div key={i} style={s.testimonialCard} className="glass">
                <div style={s.testimonialHeader}>
                  <div style={s.testimonialAvatar}>{t.avatar}</div>
                  <div>
                    <div style={s.testimonialName}>{t.name}</div>
                    <div style={s.testimonialRole}>{t.role}</div>
                  </div>
                  <div style={s.testimonialScore}>
                    <div style={s.testimonialScoreNum}>{t.score}</div>
                    <div style={s.testimonialScoreLabel}>avg score</div>
                  </div>
                </div>
                <p style={s.testimonialText}>"{t.text}"</p>
                <div style={s.testimonialStars}>{'⭐'.repeat(5)}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section id="pricing" style={s.section}>
        <div style={s.sectionInner}>
          <div style={s.sectionBadge}>Pricing</div>
          <h2 style={s.sectionTitle}>Start free.<br /><span className="gradient-text">Upgrade when ready.</span></h2>
          <div style={s.pricingGrid}>
            <div style={s.pricingCard} className="glass">
              <div style={s.pricingName}>Free</div>
              <div style={s.pricingPrice}>$0<span style={s.pricingPer}>/month</span></div>
              <div style={s.pricingDesc}>Perfect to get started</div>
              <div style={s.pricingFeatures}>
                {['5 sessions/month', 'All 8 roles', 'AI scoring', 'Basic feedback'].map(f => (
                  <div key={f} style={s.pricingFeature}><span style={{ color: 'var(--green)' }}>✓</span> {f}</div>
                ))}
              </div>
              <button className="btn-primary" style={s.pricingBtn} onClick={() => navigate('/register')}>Get Started Free</button>
            </div>
            <div style={{ ...s.pricingCard, ...s.pricingCardPro }}>
              <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                <div style={s.pricingProBadge}>Most Popular</div>
                <div style={{ background: 'rgba(139,92,246,0.2)', border: '1px solid rgba(139,92,246,0.4)', color: '#a78bfa', fontSize: '10px', padding: '2px 10px', borderRadius: '100px', letterSpacing: '1.5px', textTransform: 'uppercase' }}>Coming Soon</div>
              </div>
              <div style={s.pricingName}>Pro</div>
              <div style={{ ...s.pricingPrice, color: 'var(--purple-bright)' }}>$12<span style={s.pricingPer}>/month</span></div>
              <div style={s.pricingDesc}>For serious candidates</div>
              <div style={s.pricingFeatures}>
                {['Unlimited sessions', 'All 8 roles', 'Advanced AI scoring', 'Detailed feedback', 'Progress tracking', 'Voice input', 'Streak system', 'Priority support'].map(f => (
                  <div key={f} style={s.pricingFeature}><span style={{ color: 'var(--purple-bright)' }}>✓</span> {f}</div>
                ))}
              </div>
              <button className="btn-primary" style={{ ...s.pricingBtn, animation: 'pulse-glow 2s ease infinite' }} onClick={() => navigate('/register')}>Start Pro Trial →</button>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" style={s.section}>
        <div style={s.sectionInner}>
          <div style={s.sectionBadge}>FAQ</div>
          <h2 style={s.sectionTitle}>Questions?<br /><span className="gradient-text">Answered.</span></h2>
          <div style={s.faqList}>
            {FAQS.map((faq, i) => <FAQItem key={i} q={faq.q} a={faq.a} />)}
          </div>
        </div>
      </section>

      {/* FINAL CTA */}
      <section style={s.ctaSection}>
        <div style={s.ctaInner}>
          <div className="animate-float" style={s.ctaGhost}>👻</div>
          <h2 style={s.ctaTitle}>Your dream internship<br /><span className="gradient-text">is one practice away.</span></h2>
          <p style={s.ctaSub}>Join thousands of students who used InterviewGhost to land offers at Google, Meta, Apple, and more.</p>
          <button className="btn-primary" style={s.ctaBtn} onClick={() => navigate('/register')}>🚀 Start Practicing Free Today</button>
        </div>
      </section>

      {/* FOOTER */}
      <footer style={s.footer}>
        <div style={s.footerInner}>
          <div style={s.footerLogo}>
            <span>👻</span>
            <span style={s.footerBrand}>Interview<span className="gradient-text">Ghost</span></span>
          </div>
          <div style={s.footerText}>
            Built with 💜 by{' '}
            <span style={{ color: 'var(--purple-bright)', fontWeight: 600 }}>Smit Kakadiya</span>
            {' '}· SF State Sophomore
          </div>
          <div style={s.footerLinks}>
            <span style={s.footerLink}>Privacy Policy</span>
            <span style={{ color: 'var(--text-muted)' }}>·</span>
            <span style={s.footerLink}>Terms</span>
            <span style={{ color: 'var(--text-muted)' }}>·</span>
            <a href="https://github.com/KakadiyaSmit/interviewghost" target="_blank" rel="noreferrer" style={s.footerLink}>GitHub</a>
          </div>
          <div style={s.footerText}>© 2026 InterviewGhost. All rights reserved.</div>
        </div>
      </footer>
    </div>
  )
}

function makeStyles(isMobile) {
  return {
    page: { background: 'var(--bg-primary)', minHeight: '100vh', overflowX: 'hidden', position: 'relative' },
    orb1: { position: 'fixed', top: '-20%', left: '-10%', width: '700px', height: '700px', background: 'radial-gradient(circle, rgba(139,92,246,0.12) 0%, transparent 70%)', borderRadius: '50%', pointerEvents: 'none', zIndex: 0, animation: 'orb-float 10s ease-in-out infinite' },
    orb2: { position: 'fixed', top: '30%', right: '-10%', width: '600px', height: '600px', background: 'radial-gradient(circle, rgba(34,211,238,0.08) 0%, transparent 70%)', borderRadius: '50%', pointerEvents: 'none', zIndex: 0, animation: 'orb-float 14s ease-in-out infinite reverse' },
    orb3: { position: 'fixed', bottom: '-20%', left: '30%', width: '500px', height: '500px', background: 'radial-gradient(circle, rgba(139,92,246,0.08) 0%, transparent 70%)', borderRadius: '50%', pointerEvents: 'none', zIndex: 0, animation: 'orb-float 12s ease-in-out infinite' },
    grid: { position: 'fixed', inset: 0, zIndex: 0, backgroundImage: 'linear-gradient(rgba(139,92,246,0.025) 1px, transparent 1px), linear-gradient(90deg, rgba(139,92,246,0.025) 1px, transparent 1px)', backgroundSize: '40px 40px', pointerEvents: 'none' },

    // NAV
    nav: { position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100, padding: '0 24px', background: 'rgba(5,5,8,0.85)', backdropFilter: 'blur(20px)', borderBottom: '1px solid rgba(255,255,255,0.06)' },
    navInner: { maxWidth: '1100px', margin: '0 auto', height: '64px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
    navLogo: { display: 'flex', alignItems: 'center', gap: '10px' },
    navGhost: { fontSize: '24px' },
    navBrand: { fontFamily: 'var(--font-display)', fontSize: isMobile ? '17px' : '20px', fontWeight: 800, letterSpacing: '-0.02em' },
    navLinks: { display: 'flex', gap: '32px' },
    navLink: { color: 'var(--text-muted)', textDecoration: 'none', fontSize: '14px', fontWeight: 500, transition: 'color 0.2s ease' },
    navActions: { display: 'flex', gap: '12px', alignItems: 'center' },
    navLoginBtn: { background: 'transparent', border: '1px solid rgba(255,255,255,0.1)', color: 'var(--text-secondary)', padding: '8px 16px', borderRadius: '8px', cursor: 'pointer', fontSize: '14px', fontFamily: 'var(--font-body)' },
    navCTABtn: { padding: isMobile ? '8px 14px' : '8px 20px', fontSize: '14px' },

    // HERO
    hero: { position: 'relative', zIndex: 1, textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '24px', padding: isMobile ? '110px 20px 60px' : '140px 24px 80px' },
    heroBadge: { display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '8px 18px', borderRadius: '50px', background: 'rgba(139,92,246,0.1)', border: '1px solid rgba(139,92,246,0.2)', color: 'var(--purple-bright)', fontSize: isMobile ? '11px' : '13px', fontWeight: 500, textAlign: 'center' },
    heroBadgeDot: { width: '6px', height: '6px', borderRadius: '50%', background: 'var(--purple-bright)', boxShadow: '0 0 8px var(--purple-glow)', display: 'inline-block', flexShrink: 0 },
    heroTitle: { fontFamily: 'var(--font-display)', fontSize: isMobile ? 'clamp(22px, 6vw, 30px)' : 'clamp(28px, 4vw, 36px)', fontWeight: 700, lineHeight: 1.3, letterSpacing: '-0.01em', maxWidth: '700px', textAlign: 'center' },
    heroRoleWrap: { display: 'block', fontSize: isMobile ? 'clamp(24px, 7vw, 32px)' : 'clamp(30px, 4vw, 40px)', whiteSpace: 'normal', wordBreak: 'break-word' },
    cursor: { color: 'var(--purple-bright)', marginLeft: '2px' },
    heroSub: { color: 'var(--text-secondary)', fontSize: isMobile ? '15px' : '16px', lineHeight: 1.7, maxWidth: '520px', textAlign: 'center' },
    heroActions: { display: 'flex', gap: '16px', alignItems: 'center', flexWrap: 'wrap', justifyContent: 'center', flexDirection: isMobile ? 'column' : 'row' },
    heroCTA: { padding: isMobile ? '14px 28px' : '16px 36px', fontSize: '16px', fontWeight: 700, width: isMobile ? '100%' : 'auto' },
    heroSecondary: { background: 'transparent', border: 'none', color: 'var(--text-muted)', fontSize: '15px', cursor: 'pointer', fontFamily: 'var(--font-body)', transition: 'color 0.2s ease' },
    socialProof: { display: 'flex', alignItems: 'center', gap: '12px' },
    avatarStack: { display: 'flex' },
    avatar: { width: '32px', height: '32px', borderRadius: '50%', background: 'rgba(139,92,246,0.2)', border: '2px solid var(--bg-primary)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '16px' },
    socialText: { color: 'var(--text-muted)', fontSize: '14px' },
    heroVisual: { position: 'relative', width: '100%', maxWidth: isMobile ? '100%' : '720px', marginTop: '24px', padding: isMobile ? '0 4px' : '0 24px' },
    mockCard: { background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 40px 80px rgba(0,0,0,0.4), 0 0 0 1px rgba(139,92,246,0.1)' },
    mockHeader: { display: 'flex', alignItems: 'center', gap: '12px', padding: '14px 20px', background: 'rgba(255,255,255,0.03)', borderBottom: '1px solid rgba(255,255,255,0.06)' },
    mockDots: { display: 'flex', gap: '6px' },
    mockDot: { width: '10px', height: '10px', borderRadius: '50%' },
    mockTitle: { color: 'var(--text-muted)', fontSize: '12px', fontFamily: 'var(--font-mono)' },
    mockBody: { padding: '24px', display: 'flex', flexDirection: 'column', gap: '20px' },
    mockQuestion: { display: 'flex', flexDirection: 'column', gap: '12px' },
    mockBadges: { display: 'flex', gap: '8px' },
    mockQuestionText: { color: 'var(--text-primary)', fontSize: '15px', lineHeight: 1.6, textAlign: 'left' },
    mockScores: { display: 'flex', flexDirection: 'column', gap: '10px' },
    mockScoreRow: { display: 'flex', alignItems: 'center', gap: '12px' },
    mockScoreLabel: { color: 'var(--text-muted)', fontSize: '12px', width: '120px', textAlign: 'left' },
    mockScoreBar: { flex: 1, height: '6px', background: 'rgba(255,255,255,0.06)', borderRadius: '3px', overflow: 'hidden' },
    mockScoreFill: { height: '100%', borderRadius: '3px' },
    mockScoreNum: { fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 600, width: '30px', textAlign: 'right' },
    mockFeedback: { padding: '12px 16px', background: 'rgba(16,185,129,0.05)', border: '1px solid rgba(16,185,129,0.1)', borderRadius: '10px', textAlign: 'left' },
    floatBadge1: { position: 'absolute', top: '-20px', right: '-20px', background: 'rgba(139,92,246,0.15)', backdropFilter: 'blur(10px)', border: '1px solid rgba(139,92,246,0.3)', borderRadius: '50px', padding: '10px 18px', color: 'var(--purple-bright)', fontSize: '13px', fontWeight: 600, display: 'flex', gap: '8px', alignItems: 'center' },
    floatBadge2: { position: 'absolute', bottom: '-20px', left: '-20px', background: 'rgba(34,211,238,0.1)', backdropFilter: 'blur(10px)', border: '1px solid rgba(34,211,238,0.2)', borderRadius: '50px', padding: '10px 18px', color: 'var(--cyan)', fontSize: '13px', fontWeight: 600, display: 'flex', gap: '8px', alignItems: 'center' },

    // STATS
    statsSection: { position: 'relative', zIndex: 1, borderTop: '1px solid rgba(255,255,255,0.06)', borderBottom: '1px solid rgba(255,255,255,0.06)', background: 'rgba(255,255,255,0.02)', padding: isMobile ? '36px 20px' : '48px 24px' },
    statsInner: { maxWidth: '900px', margin: '0 auto', display: 'grid', gridTemplateColumns: isMobile ? 'repeat(2, 1fr)' : 'repeat(4, 1fr)', gap: isMobile ? '24px' : '32px' },
    statItem: { textAlign: 'center' },
    statValue: { fontFamily: 'var(--font-display)', fontSize: isMobile ? '32px' : '42px', fontWeight: 800, background: 'linear-gradient(135deg, var(--purple-bright), var(--cyan))', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' },
    statLabel: { color: 'var(--text-muted)', fontSize: '13px', marginTop: '4px' },

    // SECTIONS
    section: { position: 'relative', zIndex: 1, padding: isMobile ? '60px 20px' : '100px 24px' },
    sectionInner: { maxWidth: '1100px', margin: '0 auto', textAlign: 'center' },
    sectionBadge: { display: 'inline-block', padding: '6px 16px', borderRadius: '50px', background: 'rgba(139,92,246,0.1)', border: '1px solid rgba(139,92,246,0.2)', color: 'var(--purple-bright)', fontSize: '12px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '20px' },
    sectionTitle: { fontFamily: 'var(--font-display)', fontSize: isMobile ? 'clamp(28px, 7vw, 40px)' : 'clamp(32px, 4vw, 52px)', fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.2, marginBottom: '16px' },
    sectionSub: { color: 'var(--text-secondary)', fontSize: '17px', lineHeight: 1.7, maxWidth: '540px', margin: '0 auto 56px' },

    // FEATURES
    featuresGrid: { display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(3, 1fr)', gap: '20px', textAlign: 'left' },
    featureCard: { padding: '28px', borderRadius: '20px', display: 'flex', flexDirection: 'column', gap: '14px' },
    featureIcon: { width: '48px', height: '48px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '22px' },
    featureTitle: { fontFamily: 'var(--font-display)', fontSize: '17px', fontWeight: 700 },
    featureDesc: { color: 'var(--text-secondary)', fontSize: '14px', lineHeight: 1.7 },

    // TESTIMONIALS
    testimonialsGrid: { display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(3, 1fr)', gap: '20px', textAlign: 'left' },
    testimonialCard: { padding: '28px', display: 'flex', flexDirection: 'column', gap: '16px' },
    testimonialHeader: { display: 'flex', alignItems: 'center', gap: '12px' },
    testimonialAvatar: { width: '44px', height: '44px', borderRadius: '50%', background: 'rgba(139,92,246,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '22px', flexShrink: 0 },
    testimonialName: { fontWeight: 700, fontSize: '15px' },
    testimonialRole: { color: 'var(--purple-bright)', fontSize: '12px' },
    testimonialScore: { marginLeft: 'auto', textAlign: 'center' },
    testimonialScoreNum: { fontFamily: 'var(--font-mono)', fontSize: '24px', fontWeight: 700, color: 'var(--green)' },
    testimonialScoreLabel: { color: 'var(--text-muted)', fontSize: '10px' },
    testimonialText: { color: 'var(--text-secondary)', fontSize: '14px', lineHeight: 1.7 },
    testimonialStars: { fontSize: '12px' },

    // PRICING
    pricingGrid: { display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(2, 1fr)', gap: '20px', maxWidth: '700px', margin: '0 auto', textAlign: 'left' },
    pricingCard: { padding: '32px', borderRadius: '24px', display: 'flex', flexDirection: 'column', gap: '16px', position: 'relative' },
    pricingCardPro: { background: 'linear-gradient(135deg, rgba(139,92,246,0.1), rgba(34,211,238,0.05))', border: '1px solid rgba(139,92,246,0.3)' },
    pricingProBadge: { position: 'absolute', top: '-12px', left: '50%', transform: 'translateX(-50%)', background: 'linear-gradient(135deg, var(--purple), #6d28d9)', color: '#fff', padding: '4px 16px', borderRadius: '50px', fontSize: '11px', fontWeight: 700, whiteSpace: 'nowrap' },
    pricingName: { fontFamily: 'var(--font-display)', fontSize: '18px', fontWeight: 700 },
    pricingPrice: { fontFamily: 'var(--font-display)', fontSize: '42px', fontWeight: 800 },
    pricingPer: { fontSize: '16px', color: 'var(--text-muted)', fontFamily: 'var(--font-body)' },
    pricingDesc: { color: 'var(--text-muted)', fontSize: '14px' },
    pricingFeatures: { display: 'flex', flexDirection: 'column', gap: '10px', flex: 1 },
    pricingFeature: { color: 'var(--text-secondary)', fontSize: '14px', display: 'flex', gap: '8px' },
    pricingBtn: { width: '100%', padding: '14px', fontSize: '15px', marginTop: '8px' },

    // FAQ
    faqList: { maxWidth: '700px', margin: '0 auto', textAlign: 'left' },

    // CTA
    ctaSection: { position: 'relative', zIndex: 1, padding: isMobile ? '60px 20px' : '100px 24px', textAlign: 'center', background: 'linear-gradient(135deg, rgba(139,92,246,0.06), rgba(34,211,238,0.03))' },
    ctaInner: { maxWidth: '700px', margin: '0 auto', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '24px' },
    ctaGhost: { fontSize: isMobile ? '56px' : '72px' },
    ctaTitle: { fontFamily: 'var(--font-display)', fontSize: isMobile ? 'clamp(28px, 7vw, 40px)' : 'clamp(32px, 4vw, 52px)', fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1.2 },
    ctaSub: { color: 'var(--text-secondary)', fontSize: isMobile ? '15px' : '17px', lineHeight: 1.7 },
    ctaBtn: { padding: isMobile ? '14px 28px' : '18px 48px', fontSize: isMobile ? '15px' : '17px', fontWeight: 700, width: isMobile ? '100%' : 'auto' },

    // FOOTER
    footer: { position: 'relative', zIndex: 1, borderTop: '1px solid rgba(255,255,255,0.06)', padding: '40px 24px' },
    footerInner: { maxWidth: '1100px', margin: '0 auto', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '12px', textAlign: 'center' },
    footerLogo: { display: 'flex', alignItems: 'center', gap: '8px' },
    footerBrand: { fontFamily: 'var(--font-display)', fontSize: '18px', fontWeight: 800 },
    footerText: { color: 'var(--text-muted)', fontSize: '13px' },
    footerLinks: { display: 'flex', gap: '12px', alignItems: 'center', flexWrap: 'wrap', justifyContent: 'center' },
    footerLink: { color: 'var(--text-muted)', fontSize: '13px', cursor: 'pointer', textDecoration: 'none', transition: 'color 0.2s ease' },
  }
}